//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerComment
    {
        public int id { get; set; }
        public int AnswerId { get; set; }
        public string body { get; set; }
        public int commentIndex { get; set; }
    }
}
