//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GeneralDbEntities1 : DbContext
    {
        public GeneralDbEntities1()
            : base("name=GeneralDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Vote> Votes { get; set; }
    
        public virtual int VoteCRUD(string userName, Nullable<int> questionId, Nullable<bool> upvote)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var questionIdParameter = questionId.HasValue ?
                new ObjectParameter("questionId", questionId) :
                new ObjectParameter("questionId", typeof(int));
    
            var upvoteParameter = upvote.HasValue ?
                new ObjectParameter("upvote", upvote) :
                new ObjectParameter("upvote", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VoteCRUD", userNameParameter, questionIdParameter, upvoteParameter);
        }
    }
}
