//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Votes1 = new HashSet<Vote>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public string tags { get; set; }
        public Nullable<int> votes { get; set; }
        public string userName { get; set; }
        public Nullable<bool> closed { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastUpdatedDate { get; set; }
        public Nullable<long> viewCount { get; set; }
    
        public virtual ICollection<Vote> Votes1 { get; set; }
    }
}
